version: '3.8'

services:

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    container_name: mongodb-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo

    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

    ports:
      - "8001:8081"
